# Generated by Django 6.0.7 on 2026-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('tags', models.JSONField()),
                ('eaten_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['eaten_at'], name='meals_meal_eaten_a_4eb214_idx')],
            },
        ),
    ]
